//
// Created by olcay on 31.01.2019.
//

#ifndef CLASSIFICATION_STATISTICALTESTRESULTSTYPE_H
#define CLASSIFICATION_STATISTICALTESTRESULTSTYPE_H

enum class StatisticalTestResultType {
    FAILED_TO_REJECT, REJECT
};


#endif //CLASSIFICATION_STATISTICALTESTRESULTSTYPE_H
