//
// Created by Olcay Taner YILDIZ on 12.08.2021.
//

#ifndef CLASSIFICATION_ACTIVATIONFUNCTION_H
#define CLASSIFICATION_ACTIVATIONFUNCTION_H

enum class ActivationFunction{
    SIGMOID,
    TANH,
    RELU
};

#endif //CLASSIFICATION_ACTIVATIONFUNCTION_H
